// "use client"
// import LoginForm from './components/LoginForm'
// import SignupForm from './components/SignupForm';

// import {BrowserRouter, Routes, Route} from 'react-router-dom'
// import Logout from './components/Logout';

// import ProfilePageWithEdit from './components/ProfilePageWithEdit';



// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <BrowserRouter>
//       <body>{children}</body>
//       <SignupForm/>
//       <LoginForm/>
//       <Logout/>
//       {/* <ProfilePage/> */}
//       <ProfilePageWithEdit/>
//       </BrowserRouter>
//     </html>
//   );
// }

import "./globals.css";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}

    

      </body>
    </html>
  );
}